CREATE TABLE Cliente (
  CPF VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
  Nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Consulta (
  id SERIAL PRIMARY KEY,
  Valor DOUBLE PRECISION NOT NULL,
  NumPrestacoes INTEGER NOT NULL,
  Juros DOUBLE PRECISION NOT NULL,
  Montante DOUBLE PRECISION NOT NULL,
  Prestacoes VARCHAR(255) NOT NULL,
  ClienteCPF VARCHAR(255) REFERENCES Cliente(CPF)
);