import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body
        className={`${inter.className} bg-background bg-no-repeat overflow-y-auto h-screen w-screen flex justify-center items-center overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
